Repository hmcts/ccpay-paymentoutcome-web, pull requests merged in 2024-06, with the labels that each got.

#248 PAY-7168 cve suppression
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-paymentoutcome-web-pr-248

#249 PAY-7141: Vulnernability fixes
  .gitignore
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-paymentoutcome-web-pr-249

#262 PAY-7178: Update to remove braces vulnerability
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-paymentoutcome-web-pr-262
